import type { Project } from "./content";
import { GH } from "./content-shared";

/** Projetos — parte 1/3. A ordem editorial mora em src/data/projects.ts. */
export const PROJECTS_1: Project[] = [
  {
    slug: "milsaca",
    category: "sistema-saas",
    title: "Milsaca",
    tagline: { pt: "SaaS sob medida · plataforma multi-tenant", en: "Custom SaaS · multi-tenant platform", es: "SaaS a medida · plataforma multi-tenant" },
    problem: { pt: "Um setor inteiro rodava no improviso entre planilhas e WhatsApp, sem um sistema único.", en: "A whole sector ran improvised between spreadsheets and WhatsApp, with no single system.", es: "Un sector entero funcionaba a la improvisada, entre planillas y WhatsApp, sin un sistema único." },
    result: { pt: "SaaS multi-tenant (web + mobile) com painéis por papel, automações e dados seguros (RLS). Prova de que entrego produto complexo de ponta a ponta.", en: "Multi-tenant SaaS (web + mobile) with role-based panels, automations and secure data (RLS). Proof I ship complex products end to end.", es: "SaaS multi-tenant (web + mobile) con paneles por rol, automatizaciones y datos seguros (RLS). Prueba de que entrego producto complejo de punta a punta." },
    stack: ["Next.js", "Expo", "Supabase", "PostgreSQL", "TypeScript"],
    metric: { pt: "Multi-tenant · web + mobile · RLS", en: "Multi-tenant · web + mobile · RLS", es: "Multi-tenant · web + mobile · RLS" },
    status: { pt: "Em desenvolvimento", en: "In development", es: "En desarrollo" },
    note: {
      pt: "SaaS em desenvolvimento ativo.",
      en: "SaaS under active development.",
      es: "SaaS en desarrollo activo.",
    },
    featured: true,
    image: "/shots/milsaca.webp",
    caseStudy: {
      narrative: [
        {
          pt: "Monorepo Turborepo + pnpm com três frentes num só backend: Next.js 16 (App Router) pro web, que sozinho já cobre três painéis (produtor, corretora e admin da plataforma), e Expo Router pro app mobile do produtor. Web e mobile falam com o mesmo Supabase através de um pacote compartilhado (@milsaca/db) com três camadas de client: uma com cookie de sessão pro server, uma sem cookie (só a chave pública) pra rotas com cache, e uma com secure-store pro mobile.",
          en: "A Turborepo + pnpm monorepo with three fronts on one backend: Next.js 16 (App Router) for web, which alone covers three panels (producer, broker, and platform admin), and Expo Router for the producer's mobile app. Web and mobile talk to the same Supabase through a shared package (@milsaca/db) with three client layers: one with a session cookie for the server, one cookie-less (public key only) for cached routes, and one with secure-store for mobile.",
          es: "Monorepo Turborepo + pnpm con tres frentes sobre un solo backend: Next.js 16 (App Router) para la web, que por sí sola ya cubre tres paneles (productor, corredora y admin de la plataforma), y Expo Router para la app mobile del productor. Web y mobile hablan con el mismo Supabase a través de un paquete compartido (@milsaca/db) con tres capas de client: una con cookie de sesión para el server, una sin cookie (solo la clave pública) para rutas con caché, y una con secure-store para mobile.",
        },
        {
          pt: "Multi-tenant de verdade, não só \"filtro no WHERE\": toda tabela do schema público tem Row Level Security habilitada, sem exceção, com isolamento por corretora_id garantido no banco, não na aplicação. Papéis (produtor/corretora/admin) vivem num array na tabela de perfil, permitindo o mesmo e-mail acumular mais de um papel; o admin da plataforma fica numa tabela própria, fora do enum de papéis, pra não vazar por engano num RLS mal escrito.",
          en: "Multi-tenant for real, not just a \"WHERE filter\": every table in the public schema has Row Level Security enabled, no exceptions, with isolation by corretora_id enforced in the database, not in the application layer. Roles (producer/broker/admin) live in an array on the profile table, letting the same email hold more than one role; the platform admin sits in its own table, outside the role enum, so a sloppy RLS policy can't accidentally leak it.",
          es: "Multi-tenant de verdad, no solo \"un filtro en el WHERE\": toda tabla del schema público tiene Row Level Security habilitado, sin excepción, con aislamiento por corretora_id garantizado en la base de datos, no en la aplicación. Los roles (productor/corredora/admin) viven en un array en la tabla de perfil, lo que permite que el mismo e-mail acumule más de un rol; el admin de la plataforma está en una tabla propia, fuera del enum de roles, para que no se filtre por error en un RLS mal escrito.",
        },
        {
          pt: "A decisão de autenticação é um bom exemplo de aprender com o próprio produto: começou com magic link e foi trocada por OTP de 6 dígitos por e-mail, porque o Gmail Safe Links faz prefetch automático do link (pra escanear por segurança) e acaba \"queimando\" o token de uso único antes do usuário clicar. É um bug sutil que só aparece em produção, com e-mails reais.",
          en: "The auth decision is a good example of learning from the product itself: it started with magic links and was switched to a 6-digit email OTP, because Gmail Safe Links auto-prefetches the link (to scan it for safety) and ends up \"burning\" the one-time token before the user even clicks. It's a subtle bug that only shows up in production, with real email providers.",
          es: "La decisión de autenticación es un buen ejemplo de aprender del propio producto: empezó con magic link y se cambió por OTP de 6 dígitos por e-mail, porque Gmail Safe Links hace prefetch automático del link (para escanearlo por seguridad) y termina \"quemando\" el token de un solo uso antes de que el usuario haga clic. Es un bug sutil que solo aparece en producción, con e-mails reales.",
        },
        {
          pt: "O diferencial de domínio é a classificação COB (Instrução Normativa MAPA nº 8/2003): a lógica de tipos, defeitos, peneira e bebida do café cru foi extraída pra um pacote puro (@milsaca/cob), sem dependência de runtime, testável isoladamente. O laudo gerado tem PDF com QR code e uma página pública de verificação, dando ao produtor algo que hoje é feito no papel ou de cabeça.",
          en: "The domain differentiator is the COB classification (Brazilian MAPA regulation IN 8/2003): the logic for coffee type, defects, screen size and cup quality was extracted into a pure package (@milsaca/cob), with no runtime dependencies, independently testable. The generated report ships as a PDF with a QR code and a public verification page, giving the producer something that today is done on paper or from memory.",
          es: "El diferencial de dominio es la clasificación COB (Instrucción Normativa MAPA nº 8/2003): la lógica de tipos, defectos, criba y bebida del café verde se extrajo a un paquete puro (@milsaca/cob), sin dependencias de runtime, testeable de forma aislada. El informe generado tiene PDF con código QR y una página pública de verificación, y le da al productor algo que hoy se hace en papel o de memoria.",
        },
      ],
      highlights: [
        {
          label: { pt: "Multi-tenant via RLS", en: "Multi-tenant via RLS", es: "Multi-tenant vía RLS" },
          detail: { pt: "Isolamento por corretora_id garantido no banco, não na aplicação. RLS em toda tabela.", en: "Isolation by corretora_id enforced in the database, not the app. RLS on every table.", es: "Aislamiento por corretora_id garantizado en la base de datos, no en la aplicación. RLS en toda tabla." },
        },
        {
          label: { pt: "Laudo COB digital", en: "Digital COB report", es: "Informe COB digital" },
          detail: { pt: "Motor de classificação da IN 8/2003 (MAPA) em pacote puro, com PDF + QR de verificação pública.", en: "IN 8/2003 (MAPA) classification engine as a pure package, with PDF + public QR verification.", es: "Motor de clasificación de la IN 8/2003 (MAPA) en paquete puro, con PDF + QR de verificación pública." },
        },
        {
          label: { pt: "Cotações ao vivo", en: "Live market quotes", es: "Cotizaciones en vivo" },
          detail: { pt: "CEPEA, ICE NY Coffee C e PTAX (BCB) sincronizados via edge function agendada.", en: "CEPEA, ICE NY Coffee C and PTAX (Brazil's central bank) synced via a scheduled edge function.", es: "CEPEA, ICE NY Coffee C y PTAX (BCB) sincronizados vía edge function programada." },
        },
        {
          label: { pt: "Web + mobile, um backend", en: "Web + mobile, one backend", es: "Web + mobile, un solo backend" },
          detail: { pt: "Next.js 16 e Expo Router compartilhando o mesmo Supabase por um pacote de clients em camadas.", en: "Next.js 16 and Expo Router sharing the same Supabase through a layered client package.", es: "Next.js 16 y Expo Router compartiendo el mismo Supabase por un paquete de clients en capas." },
        },
      ],
      gallery: [
        { src: "/shots/milsaca/landing.webp", alt: { pt: "Página pública do Milsaca", en: "Milsaca public landing page", es: "Página pública de Milsaca" } },
        { src: "/shots/milsaca/painel-corretora.webp", alt: { pt: "Painel da corretora (dados de demonstração)", en: "Broker panel (demo data)", es: "Panel de la corredora (datos de demostración)" } },
        { src: "/shots/milsaca/laudo-cob.webp", alt: { pt: "Laudo COB digital do produtor (dados de demonstração)", en: "Producer's digital COB report (demo data)", es: "Informe COB digital del productor (datos de demostración)" } },
      ],
    },
  },
  {
    slug: "millead",
    category: "sistema-saas",
    title: "MilLead",
    tagline: { pt: "CRM com IA · prospecção de clientes", en: "AI-powered CRM · client prospecting", es: "CRM con IA · prospección de clientes" },
    problem: { pt: "Prospectar clientes pra agência era manual: achar negócios com site fraco, avaliar um por um e escrever cada abordagem do zero.", en: "Prospecting clients for the agency was manual: finding businesses with weak websites, assessing each one and writing every outreach from scratch.", es: "Prospectar clientes para la agencia era manual: encontrar negocios con sitio débil, evaluarlos uno por uno y escribir cada abordaje desde cero." },
    result: { pt: "CRM interno completo: pipeline kanban, auditoria automática de sites (performance, SEO, segurança), IA que pontua leads, escreve mensagens e gera landing pages de demonstração publicáveis com um clique.", en: "A complete internal CRM: kanban pipeline, automated website audits (performance, SEO, security), and AI that scores leads, writes outreach and generates demo landing pages publishable in one click.", es: "CRM interno completo: pipeline kanban, auditoría automática de sitios (performance, SEO, seguridad), IA que puntúa leads, escribe mensajes y genera landing pages de demostración publicables con un clic." },
    stack: ["Next.js", "Express", "PostgreSQL", "Prisma", "BullMQ", "Claude API"],
    metric: { pt: "Auditoria de sites · IA · landing pages", en: "Website audits · AI · landing pages", es: "Auditoría de sitios · IA · landing pages" },
    repos: [{ label: "Código", url: `${GH}/millead` }],
    status: { pt: "Ferramenta interna da MilWeb", en: "MilWeb internal tool", es: "Herramienta interna de MilWeb" },
    hideFromLists: true,
    image: "/shots/millead.webp",
    note: {
      pt: "CRM interno usado na prospecção da própria MilWeb.",
      en: "Internal CRM used in MilWeb's own prospecting.",
      es: "CRM interno usado en la prospección de la propia MilWeb.",
    },
    featured: true,
    caseStudy: {
      narrative: [
        {
          pt: "Monorepo pnpm + Turborepo com API Express em Clean Architecture (domain/application/infrastructure/interfaces) e web Next.js 15. Multi-tenant por coluna discriminadora com RLS habilitado em todas as tabelas do Postgres (Supabase), auth JWT com refresh token de rotação atômica e RBAC com catálogo de permissões por papel.",
          en: "A pnpm + Turborepo monorepo with an Express API in Clean Architecture (domain/application/infrastructure/interfaces) and a Next.js 15 web app. Multi-tenant via discriminator column with RLS enabled on every Postgres table (Supabase), JWT auth with atomic refresh-token rotation, and RBAC with a per-role permission catalog.",
          es: "Monorepo pnpm + Turborepo con API Express en Clean Architecture (domain/application/infrastructure/interfaces) y web Next.js 15. Multi-tenant por columna discriminadora con RLS habilitado en todas las tablas de Postgres (Supabase), auth JWT con refresh token de rotación atómica y RBAC con catálogo de permisos por rol.",
        },
        {
          pt: "O diferencial é o funil de prospecção automatizado: um worker BullMQ (Redis/Upstash) baixa o site do prospect e roda ~30 checagens próprias em 6 categorias (performance, SEO, acessibilidade, segurança, mobile, design), cada nota explicável check a check. Esses achados alimentam a IA (Claude, via SDK oficial): score de oportunidade 0-100 com justificativa, rascunhos de mensagem personalizados por canal e um relatório executivo do lead.",
          en: "The differentiator is the automated prospecting funnel: a BullMQ worker (Redis/Upstash) fetches the prospect's website and runs ~30 custom checks across 6 categories (performance, SEO, accessibility, security, mobile, design), every score explainable check by check. Those findings feed the AI (Claude, official SDK): a 0-100 opportunity score with rationale, per-channel personalized outreach drafts, and an executive lead report.",
          es: "El diferencial es el embudo de prospección automatizado: un worker BullMQ (Redis/Upstash) descarga el sitio del prospecto y corre ~30 chequeos propios en 6 categorías (performance, SEO, accesibilidad, seguridad, mobile, diseño), cada nota explicable chequeo por chequeo. Esos hallazgos alimentan la IA (Claude, vía SDK oficial): score de oportunidad 0-100 con justificación, borradores de mensaje personalizados por canal y un reporte ejecutivo del lead.",
        },
        {
          pt: "O fecho do funil são as landing pages geradas por IA: HTML único e autocontido (sem JS nem recursos externos), criado a partir dos dados da empresa e da auditoria, servido numa URL pública com slug não-enumerável e contador de visitas. É a demonstração \"veja como o site de vocês poderia ficar\" que a agência manda pro prospect.",
          en: "The funnel closes with AI-generated landing pages: a single self-contained HTML file (no JS, no external resources) built from the company data and the audit, served at a public URL with a non-enumerable slug and a view counter. It's the \"here's what your website could look like\" demo the agency sends to prospects.",
          es: "El cierre del embudo son las landing pages generadas por IA: HTML único y autocontenido (sin JS ni recursos externos), creado a partir de los datos de la empresa y de la auditoría, servido en una URL pública con slug no enumerable y contador de visitas. Es la demostración \"mira cómo podría quedar el sitio de ustedes\" que la agencia le manda al prospecto.",
        },
      ],
      highlights: [
        {
          label: { pt: "Auditoria de sites própria", en: "Custom website audits", es: "Auditoría de sitios propia" },
          detail: { pt: "~30 checagens em 6 categorias via fila BullMQ, sem depender de API externa, com nota explicável check a check.", en: "~30 checks across 6 categories via a BullMQ queue, with no external API and scores explainable check by check.", es: "~30 chequeos en 6 categorías vía cola BullMQ, sin depender de API externa, con nota explicable chequeo por chequeo." },
        },
        {
          label: { pt: "IA aplicada a vendas", en: "AI applied to sales", es: "IA aplicada a ventas" },
          detail: { pt: "Score de oportunidade, mensagens e relatórios com Claude, usando lead + empresa + auditoria como contexto.", en: "Opportunity scoring, outreach and reports with Claude, using lead + company + audit as context.", es: "Score de oportunidad, mensajes y reportes con Claude, usando lead + empresa + auditoría como contexto." },
        },
        {
          label: { pt: "Landing pages por IA", en: "AI-built landing pages", es: "Landing pages por IA" },
          detail: { pt: "HTML autocontido gerado sob demanda e publicado em URL pública com contador de visitas.", en: "Self-contained HTML generated on demand and published at a public URL with a view counter.", es: "HTML autocontenido generado bajo demanda y publicado en URL pública con contador de visitas." },
        },
        {
          label: { pt: "Multi-tenant seguro", en: "Secure multi-tenant", es: "Multi-tenant seguro" },
          detail: { pt: "organizationId em toda tabela + RLS no Postgres, JWT com rotação atômica de refresh token e RBAC.", en: "organizationId on every table + Postgres RLS, JWT with atomic refresh-token rotation, and RBAC.", es: "organizationId en toda tabla + RLS en Postgres, JWT con rotación atómica de refresh token y RBAC." },
        },
      ],
      gallery: [
        { src: "/shots/millead/estimates.webp", alt: { pt: "Calculadora de orçamento: horas por etapa, infraestrutura e preço em tempo real (dados de demonstração)", en: "Quote calculator: hours per stage, infrastructure and price in real time (demo data)", es: "Calculadora de presupuesto: horas por etapa, infraestructura y precio en tiempo real (datos de demostración)" } },
        { src: "/shots/millead/estimates-calc.webp", alt: { pt: "Painel do cálculo: custo real, preço mínimo, recomendado e premium (dados de demonstração)", en: "Calculation panel: real cost plus minimum, recommended and premium price (demo data)", es: "Panel del cálculo: costo real, precio mínimo, recomendado y premium (datos de demostración)" } },
        { src: "/shots/millead/kanban.webp", alt: { pt: "Pipeline kanban com valores por estágio (dados de demonstração)", en: "Kanban pipeline with per-stage totals (demo data)", es: "Pipeline kanban con valores por etapa (datos de demostración)" } },
        { src: "/shots/millead/dashboard.webp", alt: { pt: "Dashboard com financeiro, funil e leads por status (dados de demonstração)", en: "Dashboard with finance, funnel and leads by status (demo data)", es: "Dashboard con finanzas, embudo y leads por estado (datos de demostración)" } },
        { src: "/shots/millead/contracts.webp", alt: { pt: "Contratos com PDF e assinatura eletrônica (dados de demonstração)", en: "Contracts with PDF and e-signature (demo data)", es: "Contratos con PDF y firma electrónica (datos de demostración)" } },
        { src: "/shots/millead/briefings.webp", alt: { pt: "Briefings de onboarding com progresso do preenchimento (dados de demonstração)", en: "Onboarding briefings with fill-out progress (demo data)", es: "Briefings de onboarding con progreso del llenado (datos de demostración)" } },
        { src: "/shots/millead/audit.webp", alt: { pt: "Auditoria de sites: ~30 checagens em 6 categorias com nota explicável (dados de demonstração)", en: "Website audits: ~30 checks across 6 categories with explainable scores (demo data)", es: "Auditoría de sitios: ~30 chequeos en 6 categorías con nota explicable (datos de demostración)" } },
        { src: "/shots/millead/generator.webp", alt: { pt: "Gerador de prompt de site: dados do cliente viram um prompt pronto pra IA (dados de demonstração)", en: "Website prompt generator: client data becomes an AI-ready prompt (demo data)", es: "Generador de prompt de sitio: los datos del cliente se convierten en un prompt listo para la IA (datos de demostración)" } },
        { src: "/shots/millead/messages.webp", alt: { pt: "Mensagens: rascunhos de prospecção gerados por IA, por canal e status (dados de demonstração)", en: "Messages: AI-generated outreach drafts by channel and status (demo data)", es: "Mensajes: borradores de prospección generados por IA, por canal y estado (datos de demostración)" } },
        { src: "/shots/millead/agenda.webp", alt: { pt: "Agenda: calendário mensal com reuniões e tarefas + painel do dia (dados de demonstração)", en: "Agenda: monthly calendar with meetings and tasks + day panel (demo data)", es: "Agenda: calendario mensual con reuniones y tareas + panel del día (datos de demostración)" } },
        { src: "/shots/millead/proposals.webp", alt: { pt: "Propostas com valor, validade e status do envio ao aceite (dados de demonstração)", en: "Proposals with value, validity and status from sent to accepted (demo data)", es: "Propuestas con valor, vigencia y estado del envío a la aceptación (datos de demostración)" } },
        { src: "/shots/millead/companies.webp", alt: { pt: "Empresas com contato, cidade e segmento (dados de demonstração)", en: "Companies with contact, city and segment (demo data)", es: "Empresas con contacto, ciudad y segmento (datos de demostración)" } },
        { src: "/shots/millead/lead-detail.webp", alt: { pt: "Detalhe do lead: score de IA, contatos, etiquetas e abas de atividade (dados de demonstração)", en: "Lead detail: AI score, contacts, tags and activity tabs (demo data)", es: "Detalle del lead: score de IA, contactos, etiquetas y pestañas de actividad (datos de demostración)" } },
        { src: "/shots/millead/company-detail.webp", alt: { pt: "Detalhe da empresa: cadastro, sites, redes sociais e auditoria embutida (dados de demonstração)", en: "Company detail: profile, websites, socials and embedded audit (demo data)", es: "Detalle de la empresa: registro, sitios, redes sociales y auditoría integrada (datos de demostración)" } },
        { src: "/shots/millead/settings-pipeline.webp", alt: { pt: "Configuração do pipeline: estágios com cor e estágio de ganho (dados de demonstração)", en: "Pipeline settings: colored stages and won stage (demo data)", es: "Configuración del pipeline: etapas con color y etapa de ganado (datos de demostración)" } },
        { src: "/shots/millead/settings-integrations.webp", alt: { pt: "Integrações da plataforma: e-mail, WhatsApp, assinatura eletrônica e IA (dados de demonstração)", en: "Platform integrations: email, WhatsApp, e-signature and AI (demo data)", es: "Integraciones de la plataforma: e-mail, WhatsApp, firma electrónica e IA (datos de demostración)" } },
      ],
    },
  },
  {
    slug: "inkvision",
    category: "sistema-saas",
    title: "InkVision",
    tagline: { pt: "SaaS de tatuagem · simulação de tattoo com IA", en: "Tattoo SaaS · AI tattoo simulation", es: "SaaS de tatuajes · simulación de tattoo con IA" },
    problem: { pt: "Cliente de tatuagem decide no escuro: só vê como a arte vai ficar na pele durante a sessão, já com a agulha na mão.", en: "Tattoo clients decide in the dark: they only see how the art looks on skin during the session, needle already in hand.", es: "El cliente de tatuajes decide a ciegas: solo ve cómo va a quedar el arte en la piel durante la sesión, ya con la aguja en la mano." },
    result: { pt: "Simulação da tatuagem na própria foto via IA, chat com o tatuador pra aprovar o desenho, agendamento e um marketplace multi-tenant conectando clientes a estúdios e artistas.", en: "AI-powered tattoo simulation on the client's own photo, in-app chat with the artist to approve the design, scheduling and a multi-tenant marketplace connecting clients to studios and artists.", es: "Simulación del tatuaje sobre la propia foto vía IA, chat con el tatuador para aprobar el diseño, agendamiento y un marketplace multi-tenant que conecta clientes con estudios y artistas." },
    stack: ["Next.js", "TypeScript", "Prisma", "PostgreSQL", "Turborepo", "Stripe"],
    metric: { pt: "Simulação de tattoo por IA · multi-tenant", en: "AI tattoo simulation · multi-tenant", es: "Simulación de tattoo por IA · multi-tenant" },
    status: { pt: "Em desenvolvimento", en: "In development", es: "En desarrollo" },
    note: {
      pt: "SaaS em desenvolvimento ativo.",
      en: "SaaS under active development.",
      es: "SaaS en desarrollo activo.",
    },
    repos: [{ label: "Código", url: `${GH}/inkvision` }],
    featured: true,
    image: "/shots/inkvision.webp",
    caseStudy: {
      narrative: [
        {
          pt: "Monorepo pnpm + Turborepo com Clean Architecture explícita: apps/web (Next.js 15, App Router, React 19) cobre SSR/ISR das páginas públicas e Server Actions para mutações, apps/realtime isola o Socket.IO num processo dedicado (WebSocket de longa duração não convive bem com o modelo serverless do Next) e apps/worker roda os jobs assíncronos via BullMQ. A regra de negócio nunca mora nas rotas: fica em packages/core (use cases puros, sem I/O, DTOs validados com zod) que só conhece interfaces (ports) implementadas por packages/infra (repositórios Prisma). Essa decisão permitiria trocar a borda HTTP por outro framework sem tocar no domínio. Autenticação usa Better Auth em vez de Auth.js porque o plugin organization resolve membership multi-tenant nativamente (role ADMIN de plataforma e OWNER/MANAGER/ARTIST por estúdio; cliente é usuário sem membership).",
          en: "pnpm + Turborepo monorepo with explicit Clean Architecture: apps/web (Next.js 15, App Router, React 19) covers SSR/ISR for public pages and Server Actions for mutations, apps/realtime isolates Socket.IO in its own process (long-lived WebSockets don't play well with Next's serverless model) and apps/worker runs async jobs through BullMQ. Business rules never live in routes: they sit in packages/core (pure use cases, no I/O, zod-validated DTOs) which only knows interfaces (ports) implemented by packages/infra (Prisma repositories). That decision would let the HTTP edge be swapped for another framework without touching the domain. Auth uses Better Auth instead of Auth.js because its organization plugin resolves multi-tenant membership natively (platform ADMIN role plus per-studio OWNER/MANAGER/ARTIST; clients are users with no membership).",
          es: "Monorepo pnpm + Turborepo con Clean Architecture explícita: apps/web (Next.js 15, App Router, React 19) cubre SSR/ISR de las páginas públicas y Server Actions para mutaciones, apps/realtime aísla Socket.IO en un proceso dedicado (un WebSocket de larga duración no convive bien con el modelo serverless de Next) y apps/worker corre los jobs asíncronos vía BullMQ. La regla de negocio nunca vive en las rutas: está en packages/core (use cases puros, sin I/O, DTOs validados con zod), que solo conoce interfaces (ports) implementadas por packages/infra (repositorios Prisma). Esa decisión permitiría cambiar el borde HTTP por otro framework sin tocar el dominio. La autenticación usa Better Auth en vez de Auth.js porque el plugin organization resuelve la membresía multi-tenant de forma nativa (rol ADMIN de plataforma y OWNER/MANAGER/ARTIST por estudio; el cliente es un usuario sin membresía).",
        },
        {
          pt: "A simulação de tatuagem é a feature central e foi desenhada como um pipeline, não uma chamada única de IA: packages/ai expõe portas (TattooSimulationProvider, ImageGenerationProvider, SkinSegmentationProvider) e um registry que troca de provider (Fal.ai, Replicate, OpenAI, Gemini, Stable Diffusion) só com uma env var, sem nenhum caso de uso importando um provider concreto. O fluxo é segmentar a pele/parte do corpo, estimar perspectiva e curvatura, aplicar o desenho com warp na escala e posição escolhidas pelo cliente no editor (arrastar, redimensionar, rotacionar) e fechar com um passo de img2img de baixa intensidade que harmoniza sombra, textura e iluminação preservando o traço original. Como a geração leva de 10 a 60 segundos, a API só enfileira no BullMQ; o worker chama o provider e o resultado chega ao cliente por WebSocket (evento simulation:done), sem nenhum request HTTP pendurado esperando a IA responder. Cada chamada grava um AiUsageLog (provider, operação, custo) que alimenta o dashboard admin e os limites de crédito por plano.",
          en: "Tattoo simulation is the centerpiece feature and was designed as a pipeline, not a single AI call: packages/ai exposes ports (TattooSimulationProvider, ImageGenerationProvider, SkinSegmentationProvider) and a registry that swaps providers (Fal.ai, Replicate, OpenAI, Gemini, Stable Diffusion) with just an env var, with no use case importing a concrete provider. The flow is to segment skin and body part, estimate perspective and curvature, warp the artwork to the scale and position the client chose in the editor (drag, resize, rotate), then finish with a low-intensity img2img pass that blends shadow, texture and lighting while preserving the original line work. Since generation takes 10 to 60 seconds, the API only enqueues a BullMQ job; the worker calls the provider and the result reaches the client over WebSocket (simulation:done event), with no HTTP request left hanging on the AI. Every call writes an AiUsageLog (provider, operation, cost) that feeds both the admin dashboard and per-plan credit limits.",
          es: "La simulación de tatuaje es la feature central y se diseñó como un pipeline, no como una llamada única de IA: packages/ai expone puertos (TattooSimulationProvider, ImageGenerationProvider, SkinSegmentationProvider) y un registry que cambia de provider (Fal.ai, Replicate, OpenAI, Gemini, Stable Diffusion) con solo una env var, sin que ningún caso de uso importe un provider concreto. El flujo es segmentar la piel/parte del cuerpo, estimar perspectiva y curvatura, aplicar el diseño con warp en la escala y posición que el cliente eligió en el editor (arrastrar, redimensionar, rotar) y cerrar con un paso de img2img de baja intensidad que armoniza sombra, textura e iluminación preservando el trazo original. Como la generación tarda de 10 a 60 segundos, la API solo encola en BullMQ; el worker llama al provider y el resultado le llega al cliente por WebSocket (evento simulation:done), sin ningún request HTTP colgado esperando que la IA responda. Cada llamada registra un AiUsageLog (provider, operación, costo) que alimenta el dashboard admin y los límites de crédito por plan.",
        },
        {
          pt: "O isolamento multi-tenant é banco único com studioId, protegido em três camadas em vez de um filtro solto em cada query. Uma extensão do Prisma Client exige studioId em toda consulta de modelo tenant-scoped: lança erro em dev e bloqueia em prod. O RLS do Postgres (SET app.current_studio_id) segura mesmo se a camada de aplicação falhar. E uma suíte de testes tenta acesso cross-tenant em cada rota. Essa redundância pegou um bug real. O getActor() lia a tabela StudioMember, que é protegida por RLS, sem abrir o contexto de tenant nem de admin. A política nunca casava, a consulta voltava vazia mesmo com memberships reais, e o dono do estúdio acabava vendo um painel idêntico ao de um cliente comum. Em dev local o bug nunca apareceu, porque o role do Postgres usado ali ignora RLS por padrão. Só apareceu numa auditoria visual, comparando telas de verdade. O fix foi withAdmin(), seguro porque o filtro final continua sendo o próprio userId. A lição é direta: sem testar contra um role de produção, sem bypass de RLS, esse tipo de bug fica invisível por tempo indeterminado.",
          en: "Multi-tenant isolation is a single database with studioId, protected in three layers instead of a loose filter bolted onto each query. A Prisma Client extension requires studioId on every tenant-scoped model query: it throws in dev and blocks in prod. Postgres RLS (SET app.current_studio_id) holds even if the application layer fails. And a dedicated test suite attempts cross-tenant access against every route. That redundancy caught a real bug. getActor() was reading the StudioMember table, which is RLS-protected, without opening the tenant or admin context. The policy never matched, the query came back empty even with real memberships, and studio owners ended up seeing a dashboard identical to a regular client's. In local dev the bug never showed, because the Postgres role used there bypasses RLS by default. It only turned up in a visual audit, comparing real screens. The fix was withAdmin(), safe because the final filter is still the caller's own userId. The lesson is blunt: without testing against a production role, with no RLS bypass, this class of bug stays invisible indefinitely.",
          es: "El aislamiento multi-tenant es una base única con studioId, protegida en tres capas en vez de un filtro suelto en cada query. Una extensión del Prisma Client exige studioId en toda consulta de modelo tenant-scoped: lanza error en dev y bloquea en prod. El RLS de Postgres (SET app.current_studio_id) aguanta incluso si la capa de aplicación falla. Y una suite de tests intenta acceso cross-tenant en cada ruta. Esa redundancia atrapó un bug real. getActor() leía la tabla StudioMember, protegida por RLS, sin abrir el contexto de tenant ni de admin. La política nunca coincidía, la consulta volvía vacía incluso con membresías reales, y el dueño del estudio terminaba viendo un panel idéntico al de un cliente común. En dev local el bug nunca apareció, porque el rol de Postgres que se usa ahí ignora RLS por defecto. Solo apareció en una auditoría visual, comparando pantallas de verdad. El fix fue withAdmin(), seguro porque el filtro final sigue siendo el propio userId. La lección es directa: sin probar contra un rol de producción, sin bypass de RLS, ese tipo de bug queda invisible por tiempo indefinido.",
        },
        {
          pt: "O primeiro deploy real (Vercel + Neon, ambiente de teste antes da VPS de produção) revelou três bugs que nenhum ambiente anterior exercitava. A migration da constraint anti-overbooking usava tstzrange() num índice. Essa função depende do fuso da sessão (é STABLE, não IMMUTABLE) e quebra num migrate deploy de verdade. A correção foi trocar por tsrange(), que bate com o tipo real da coluna. O ambiente local usa prisma db push, que ignora SQL bruto, e o CI não rodava migrations, então o bug ficou invisível até o primeiro migrate deploy real. Teria travado o deploy na VPS também. O bundle serverless da Vercel também 'perdia' o query engine do Prisma num monorepo pnpm, resolvido com o plugin oficial de workaround, ativo só quando VERCEL=1 pra não afetar o Docker da VPS. E o rate limiting do Better Auth usava um limitador em memória, que simplesmente não funciona com múltiplas instâncias serverless. Trocado por armazenamento em banco: uma tabela RateLimit, deliberadamente fora do RLS, no mesmo padrão de User e Session, que também não são multi-tenant.",
          en: "The first real deploy (Vercel + Neon, a test environment ahead of the production VPS) surfaced three bugs no earlier environment exercised. The anti-overbooking constraint migration used tstzrange() on an index. That function depends on the session timezone (it's STABLE, not IMMUTABLE) and breaks on a real migrate deploy. The fix was switching to tsrange(), which matches the column's actual type. Local dev uses prisma db push, which ignores raw SQL, and CI never ran migrations, so the bug stayed invisible until the first real migrate deploy. It would have blocked the VPS deploy too. The Vercel serverless bundle also 'lost' Prisma's query engine inside a pnpm monorepo, fixed with the official workaround plugin, active only when VERCEL=1 so it doesn't touch the VPS's Docker build. And Better Auth's rate limiting used an in-memory limiter, which simply doesn't work across multiple serverless instances. Swapped for database-backed storage: a RateLimit table, deliberately outside RLS, following the same pattern as User and Session, which also aren't multi-tenant.",
          es: "El primer deploy real (Vercel + Neon, ambiente de prueba antes del VPS de producción) reveló tres bugs que ningún ambiente anterior ejercitaba. La migration de la constraint anti-overbooking usaba tstzrange() en un índice. Esa función depende de la zona horaria de la sesión (es STABLE, no IMMUTABLE) y se rompe en un migrate deploy de verdad. La corrección fue cambiarla por tsrange(), que coincide con el tipo real de la columna. El ambiente local usa prisma db push, que ignora SQL crudo, y el CI no corría migrations, así que el bug quedó invisible hasta el primer migrate deploy real. Habría trabado el deploy en el VPS también. El bundle serverless de Vercel además \'perdía\' el query engine de Prisma en un monorepo pnpm, resuelto con el plugin oficial de workaround, activo solo cuando VERCEL=1 para no afectar el Docker del VPS. Y el rate limiting de Better Auth usaba un limitador en memoria, que simplemente no funciona con múltiples instancias serverless. Se cambió por almacenamiento en base de datos: una tabla RateLimit, deliberadamente fuera del RLS, con el mismo patrón de User y Session, que tampoco son multi-tenant.",
        },
      ],
      highlights: [
        {
          label: { pt: "Simulação de IA como pipeline", en: "AI simulation as a pipeline", es: "Simulación de IA como pipeline" },
          detail: { pt: "Segmentação de pele, estimativa de perspectiva e curvatura, warp do desenho e img2img de baixa intensidade pra harmonizar sombra e textura. Não é uma chamada única de IA.", en: "Skin segmentation, perspective and curvature estimation, artwork warp and a low-intensity img2img pass to harmonize shadow and texture. It isn't a single AI call.", es: "Segmentación de piel, estimación de perspectiva y curvatura, warp del diseño e img2img de baja intensidad para armonizar sombra y textura. No es una llamada única de IA." },
        },
        {
          label: { pt: "Provider de IA plugável", en: "Pluggable AI provider", es: "Provider de IA conectable" },
          detail: { pt: "packages/ai troca entre Fal.ai, Replicate, OpenAI, Gemini ou Stable Diffusion só com uma env var. Nenhum caso de uso importa um provider concreto.", en: "packages/ai swaps between Fal.ai, Replicate, OpenAI, Gemini or Stable Diffusion with just an env var. No use case imports a concrete provider.", es: "packages/ai cambia entre Fal.ai, Replicate, OpenAI, Gemini o Stable Diffusion con solo una env var. Ningún caso de uso importa un provider concreto." },
        },
        {
          label: { pt: "Multi-tenant em 3 camadas", en: "3-layer multi-tenancy", es: "Multi-tenant en 3 capas" },
          detail: { pt: "Extensão do Prisma que exige studioId, Postgres RLS como defesa em profundidade e uma suíte automatizada de testes de isolamento cross-tenant.", en: "A Prisma extension enforcing studioId, Postgres RLS as defense-in-depth, and an automated cross-tenant isolation test suite.", es: "Extensión de Prisma que exige studioId, Postgres RLS como defensa en profundidad y una suite automatizada de tests de aislamiento cross-tenant." },
        },
        {
          label: { pt: "Bugs só visíveis em produção real", en: "Bugs only visible in real production", es: "Bugs solo visibles en producción real" },
          detail: { pt: "Migration com tstzrange() só quebrava num migrate deploy de verdade (dev usa db push); achada no primeiro deploy Vercel+Neon, antes de chegar na VPS.", en: "A tstzrange() migration only broke on a real migrate deploy (dev uses db push); caught during the first Vercel+Neon deploy, before it could reach the VPS.", es: "Una migration con tstzrange() solo se rompía en un migrate deploy de verdad (dev usa db push); se encontró en el primer deploy Vercel+Neon, antes de llegar al VPS." },
        },
      ],
    },
  },
  {
    slug: "rockverse",
    category: "landing-premium",
    title: "ROCKVERSE",
    tagline: { pt: "Site-experiência sobre Rock · motion design de ponta a ponta", en: "Rock experience site · end-to-end motion design", es: "Sitio-experiencia sobre rock · motion design de punta a punta" },
    problem: { pt: "Marcas de música e cultura disputam atenção em segundos, e sites institucionais comuns não geram desejo, memória nem compartilhamento.", en: "Music and culture brands fight for attention in seconds, and ordinary websites create no desire, memory or shares.", es: "Las marcas de música y cultura disputan la atención en segundos, y los sitios institucionales comunes no generan deseo, memoria ni ganas de compartir." },
    result: { pt: "Experiência imersiva pela história do rock: headline cinética letra a letra, scroll com inércia (Lenis), cursor contextual, vinis interativos com modal, timeline com scrub e seção editorial em papel. O projeto foi auditado como se eu fosse jurado de premiação e refinado em 5 fases, mantendo Lighthouse 99/100/100/100 no desktop.", en: "An immersive journey through rock history: letter-by-letter kinetic headline, inertia scrolling (Lenis), contextual cursor, interactive vinyl sleeves with modal, scrubbed timeline and a paper editorial section. The project was audited as if I were an awards juror and refined across 5 phases, keeping a 99/100/100/100 desktop Lighthouse.", es: "Experiencia inmersiva por la historia del rock: headline cinético letra por letra, scroll con inercia (Lenis), cursor contextual, vinilos interactivos con modal, timeline con scrub y sección editorial en papel. El proyecto fue auditado como si yo fuera jurado de una premiación y refinado en 5 fases, manteniendo Lighthouse 99/100/100/100 en desktop." },
    stack: ["Next.js 16", "TypeScript", "Tailwind v4", "Framer Motion", "Lenis"],
    metric: { pt: "Lighthouse 99 · A11y 100 · motion 60fps", en: "Lighthouse 99 · A11y 100 · 60fps motion", es: "Lighthouse 99 · A11y 100 · motion 60fps" },
    status: { pt: "Projeto autoral · demo", en: "Personal project · demo", es: "Proyecto propio · demo" },
    repos: [{ label: "Código", url: `${GH}/rockverse` }],
    featured: true,
    image: "/shots/rockverse.jpg",
    caseStudy: {
      narrative: [
        {
          pt: "O motion do ROCKVERSE não é biblioteca-padrão ligada no automático. O scroll passa por Lenis (lerp 0.1, smoothWheel) e o scroll-behavior: smooth nativo do CSS fica desligado, pra evitar que os dois sistemas disputem o mesmo frame. É um conflito sutil: só aparece quando alguém clica num link âncora e a página \"engasga\" no meio do scroll. O cursor customizado (CustomCursor.tsx) só ativa em pointer: fine, então telas touch nunca pagam o custo. Ele usa um anel com física de spring (stiffness 250, damping 25) seguindo um ponto rígido, e um atributo data-cursor nos elementos interativos troca o rótulo conforme o contexto, tipo \"GIRAR\" sobre um vinil. Sem re-render desnecessário, porque o estado só muda quando o valor realmente muda (bail-out do React via Object.is). A headline do hero é revelada letra a letra com máscara (overflow-hidden + translateY por motion.span, stagger de 35ms por caractere) e reage à posição do mouse com paralaxe em três camadas: fundo, título e luz radial, via useMotionValue + useSpring + useTransform. Tudo com fallback estático completo quando prefers-reduced-motion está ativo.",
          en: "ROCKVERSE's motion isn't a stock library switched to autopilot. Scroll runs through Lenis (lerp 0.1, smoothWheel) and the native CSS scroll-behavior: smooth is explicitly off, so the two systems don't fight over the same frame. It's a subtle conflict: it only shows up when someone clicks an anchor link and the page \"stutters\" mid-scroll. The custom cursor (CustomCursor.tsx) only activates on pointer: fine, so touch screens never pay the cost. It uses a spring-physics ring (stiffness 250, damping 25) trailing a rigid point, and a data-cursor attribute on interactive elements swaps the label by context, like \"SPIN\" over a vinyl record. No unnecessary re-renders, since state only updates when the value actually changes (React's Object.is bail-out). The hero headline reveals letter by letter through a mask (overflow-hidden + translateY per motion.span, 35ms stagger per character) and reacts to mouse position with three-layer parallax: background, title and radial light, via useMotionValue + useSpring + useTransform. All of it with a full static fallback whenever prefers-reduced-motion is set.",
          es: "El motion de ROCKVERSE no es una librería estándar puesta en automático. El scroll pasa por Lenis (lerp 0.1, smoothWheel) y el scroll-behavior: smooth nativo del CSS queda apagado, para evitar que los dos sistemas se disputen el mismo frame. Es un conflicto sutil: solo aparece cuando alguien hace clic en un link ancla y la página \"se traba\" a mitad del scroll. El cursor personalizado (CustomCursor.tsx) solo se activa en pointer: fine, así que las pantallas táctiles nunca pagan el costo. Usa un anillo con física de spring (stiffness 250, damping 25) que sigue a un punto rígido, y un atributo data-cursor en los elementos interactivos cambia la etiqueta según el contexto, como \"GIRAR\" sobre un vinilo. Sin re-renders innecesarios, porque el estado solo cambia cuando el valor realmente cambia (bail-out de React vía Object.is). El headline del hero se revela letra por letra con máscara (overflow-hidden + translateY por motion.span, stagger de 35ms por carácter) y reacciona a la posición del mouse con paralaje en tres capas: fondo, título y luz radial, vía useMotionValue + useSpring + useTransform. Todo con fallback estático completo cuando prefers-reduced-motion está activo.",
        },
        {
          pt: "O que separa isso de \"mais um site com fadeUp\" são as cenas ligadas ao próprio scroll, não só disparadas por ele. A timeline de décadas (History.tsx) tem uma barra de progresso em gradiente cuja escala Y vem de useScroll + useSpring do progresso da seção inteira, enquanto cada card roda seu próprio useScroll local pra dar paralaxe à imagem (-8% a 8%) e deslocar o ano lateralmente. No desktop a imagem fica sticky, o que cria profundidade sem precisar de WebGL. Na seção de álbuns, os vinis por trás das capas giram conforme o usuário rola a grade inteira (useTransform de 0 a 180 graus sobre o scrollYProgress da seção), e só ganham animate-spin-slow de verdade quando abertos no modal. O divisor de marquee vai além: em vez de rolar em velocidade fixa, aplica um skewX calculado a partir da velocidade instantânea do scroll (useVelocity sobre scrollY, mapeada pra -5°/5° com spring). O texto se inclina mais quanto mais rápido o visitante rola. É o tipo de detalhe que só existe em site que trata o scroll como instrumento, não como gatilho de fade-in.",
          en: "What separates this from \"yet another fadeUp site\" is the set of scenes tied to scroll position itself, not just triggered by it. The decades timeline (History.tsx) has a gradient progress bar whose Y-scale comes from useScroll + useSpring over the whole section's progress, while each card runs its own local useScroll to parallax its image (-8% to 8%) and shift the year label sideways. On desktop the image stays sticky, which creates depth without WebGL. In the albums section, the vinyl records behind each sleeve spin as the user scrolls through the grid (useTransform from 0 to 180 degrees over the section's scrollYProgress), and only get a real animate-spin-slow once opened in the modal. The marquee divider goes further: instead of scrolling at a fixed speed, it applies a skewX derived from the scroll's instantaneous velocity (useVelocity on scrollY, mapped to -5°/5° through a spring). The text tilts more the faster the visitor scrolls. It's the kind of detail that only shows up on sites treating scroll as an instrument rather than a fade-in trigger.",
          es: "Lo que separa esto de \"otro sitio más con fadeUp\" son las escenas ligadas al propio scroll, no solo disparadas por él. La timeline de décadas (History.tsx) tiene una barra de progreso en gradiente cuya escala Y viene de useScroll + useSpring del progreso de la sección entera, mientras cada card corre su propio useScroll local para dar paralaje a la imagen (-8% a 8%) y desplazar el año lateralmente. En desktop la imagen queda sticky, lo que crea profundidad sin necesitar WebGL. En la sección de álbumes, los vinilos detrás de las portadas giran a medida que el usuario recorre la grilla entera (useTransform de 0 a 180 grados sobre el scrollYProgress de la sección), y solo ganan un animate-spin-slow de verdad cuando se abren en el modal. El divisor de marquee va más allá: en vez de desplazarse a velocidad fija, aplica un skewX calculado a partir de la velocidad instantánea del scroll (useVelocity sobre scrollY, mapeada a -5°/5° con spring). El texto se inclina más cuanto más rápido rueda el visitante. Es el tipo de detalle que solo existe en un sitio que trata el scroll como instrumento, no como gatillo de fade-in.",
        },
        {
          pt: "Manter Lighthouse 99/100/100/100 com esse volume de efeito exigiu decisões de arquitetura, não sorte. O app/page.tsx carrega Hero, History, Navbar e a barra de progresso de forma eager, que é o que aparece na primeira dobra, e faz next/dynamic de todas as outras nove seções abaixo dela (Bands, Instruments, Genres, Festivals, Albums, HallOfFame, Curiosities, Stats, Gallery, Newsletter, Footer). Assim o bundle inicial não paga o custo de código que o usuário talvez nunca role até ver. As partículas de brasa do hero (EmberCanvas.tsx) não são componentes Framer Motion. São um canvas 2D cru desenhado a mão, com IntersectionObserver pausando o requestAnimationFrame fora da viewport e um listener de visibilitychange pausando quando a aba perde foco, além de devicePixelRatio limitado a 2 e densidade de partículas cortada pela metade no mobile. O next/image usa qualidades customizadas (qualities: [60, 75], hero explicitamente em 60) pra cortar payload de LCP sem borrar a imagem de forma perceptível. E o prefers-reduced-motion é tratado em duas camadas: um kill-switch global no CSS, que zera todas as animation-duration e transition-duration, mais checagens pontuais via useReducedMotion() nos componentes que fazem cálculo de física (parallax do hero, timeline, rotação dos vinis). Sem a segunda camada, a query CSS mataria a transition mas deixaria os cálculos de useTransform rodando a cada frame.",
          en: "Keeping a 99/100/100/100 Lighthouse score with this much motion took architectural decisions, not luck. app/page.tsx loads Hero, History, Navbar and the scroll-progress bar eagerly, which is what's visible above the fold, and wraps every other one of the nine below-the-fold sections (Bands, Instruments, Genres, Festivals, Albums, HallOfFame, Curiosities, Stats, Gallery, Newsletter, Footer) in next/dynamic. That way the initial bundle doesn't pay for code the visitor may never scroll far enough to see. The hero's ember particles (EmberCanvas.tsx) aren't Framer Motion components at all. They're a hand-rolled raw 2D canvas, with an IntersectionObserver pausing the requestAnimationFrame loop outside the viewport and a visibilitychange listener pausing it when the tab loses focus, plus devicePixelRatio capped at 2 and particle density halved on mobile. next/image uses custom quality tiers (qualities: [60, 75], the hero image explicitly pinned to 60) to cut LCP payload with no perceptible blur. And prefers-reduced-motion is handled in two layers: a global CSS kill-switch that zeroes every animation-duration and transition-duration, plus targeted useReducedMotion() checks inside components doing physics math (hero parallax, timeline, vinyl rotation). Without the second layer, the CSS media query would kill the transition but leave the underlying useTransform calculations running every frame.",
          es: "Mantener Lighthouse 99/100/100/100 con ese volumen de efectos exigió decisiones de arquitectura, no suerte. El app/page.tsx carga Hero, History, Navbar y la barra de progreso de forma eager, que es lo que aparece en el primer pliegue, y hace next/dynamic de las otras nueve secciones debajo (Bands, Instruments, Genres, Festivals, Albums, HallOfFame, Curiosities, Stats, Gallery, Newsletter, Footer). Así el bundle inicial no paga el costo de código que el usuario tal vez nunca llegue a ver. Las partículas de brasa del hero (EmberCanvas.tsx) no son componentes Framer Motion. Son un canvas 2D crudo dibujado a mano, con IntersectionObserver pausando el requestAnimationFrame fuera del viewport y un listener de visibilitychange pausando cuando la pestaña pierde el foco, además de devicePixelRatio limitado a 2 y densidad de partículas cortada a la mitad en mobile. next/image usa calidades personalizadas (qualities: [60, 75], hero explícitamente en 60) para recortar payload de LCP sin desenfocar la imagen de forma perceptible. Y prefers-reduced-motion se trata en dos capas: un kill-switch global en el CSS, que pone en cero todas las animation-duration y transition-duration, más chequeos puntuales vía useReducedMotion() en los componentes que hacen cálculo de física (paralaje del hero, timeline, rotación de los vinilos). Sin la segunda capa, la query CSS mataría la transition pero dejaría los cálculos de useTransform corriendo en cada frame.",
        },
        {
          pt: "O que mais diferencia o processo está documentado em docs/DESIGN-AUDIT.md: uma auto-auditoria de 20 problemas, escrita como se fosse um jurado de premiação avaliando o site (\"veredito geral: 7.2/10\"), cobrindo hero, paleta, tipografia, espaçamento, componentes e imagens, com um roadmap de 5 fases explícito. A Fase 4 desse roadmap, \"Motion Design\", listava exatamente o que faltava: Lenis, headline cinética, timeline com scrub, skew no marquee por velocidade. É literalmente o que está implementado no código hoje. Tratar o próprio projeto autoral como se fosse um cliente exigente, com auditoria escrita, tabela de prioridade (P0 a P3) e reavaliação de Lighthouse a cada fase, é o que separa \"fizemos um site bonito\" de um processo de design repetível.",
          en: "What most sets the process apart is documented in docs/DESIGN-AUDIT.md: a self-audit of 20 issues, written as if an awards-show juror were grading the site (\"overall verdict: 7.2/10\"), covering hero, palette, typography, spacing, components and imagery, with an explicit 5-phase roadmap. Phase 4 of that roadmap, \"Motion Design\", listed exactly what was missing: Lenis, kinetic headline, scrubbed timeline, velocity-based marquee skew. That is literally what's implemented in the code today. Treating your own passion project like a demanding client, with a written audit, a priority table (P0 through P3) and a Lighthouse re-check after every phase, is what separates \"we made a pretty site\" from a repeatable design process.",
          es: "Lo que más diferencia el proceso está documentado en docs/DESIGN-AUDIT.md: una autoauditoría de 20 problemas, escrita como si fuera un jurado de premiación evaluando el sitio (\"veredicto general: 7.2/10\"), cubriendo hero, paleta, tipografía, espaciado, componentes e imágenes, con un roadmap de 5 fases explícito. La Fase 4 de ese roadmap, \"Motion Design\", listaba exactamente lo que faltaba: Lenis, headline cinético, timeline con scrub, skew en el marquee por velocidad. Es literalmente lo que está implementado en el código hoy. Tratar el propio proyecto personal como si fuera un cliente exigente, con auditoría escrita, tabla de prioridad (P0 a P3) y reevaluación de Lighthouse en cada fase, es lo que separa \"hicimos un sitio bonito\" de un proceso de diseño repetible.",
        },
      ],
      highlights: [
        {
          label: { pt: "Scroll com física real", en: "Real-physics scroll", es: "Scroll con física real" },
          detail: { pt: "Lenis com lerp 0.1 substitui o scroll nativo, com âncoras recalculadas via offset de navbar em vez de saltos secos.", en: "Lenis at lerp 0.1 replaces native scroll, with anchors recalculated through a navbar offset instead of hard jumps.", es: "Lenis con lerp 0.1 reemplaza el scroll nativo, con anclas recalculadas vía offset de navbar en vez de saltos secos." },
        },
        {
          label: { pt: "Headline letra a letra", en: "Letter-by-letter headline", es: "Headline letra por letra" },
          detail: { pt: "Reveal por máscara com stagger de 35ms por caractere, mais paralaxe de mouse em três camadas independentes.", en: "Mask-based reveal with a 35ms stagger per character, plus three independent layers of mouse parallax.", es: "Reveal por máscara con stagger de 35ms por carácter, más paralaje de mouse en tres capas independientes." },
        },
        {
          label: { pt: "Cenas ligadas ao scroll", en: "Scroll-linked scenes", es: "Escenas ligadas al scroll" },
          detail: { pt: "Vinil que gira com o progresso da seção e marquee que se inclina conforme a velocidade instantânea do scroll.", en: "Vinyl records that spin with section scroll progress, and a marquee that skews with the scroll's instantaneous velocity.", es: "Vinilo que gira con el progreso de la sección y marquee que se inclina según la velocidad instantánea del scroll." },
        },
        {
          label: { pt: "99/100/100/100 sem atalho", en: "99/100/100/100, no shortcuts", es: "99/100/100/100 sin atajos" },
          detail: { pt: "Code-splitting por seção, partículas em canvas cru pausadas fora da viewport e reduced-motion tratado em duas camadas.", en: "Per-section code-splitting, raw-canvas particles paused off-viewport, and reduced-motion handled in two layers.", es: "Code-splitting por sección, partículas en canvas crudo pausadas fuera del viewport y reduced-motion tratado en dos capas." },
        },
      ],
      gallery: [
        { src: "/shots/rockverse/hero.webp", alt: { pt: "Hero do ROCKVERSE com headline cinética", en: "ROCKVERSE hero with kinetic headline", es: "Hero de ROCKVERSE con headline cinético" } },
        { src: "/shots/rockverse/albums.webp", alt: { pt: "Grade de vinis (Discoteca)", en: "Vinyl grid (Discography section)", es: "Grilla de vinilos (Discoteca)" } },
      ],
    },
  },
  {
    slug: "aurex-motors",
    category: "landing-premium",
    title: "AUREX MOTORS",
    tagline: { pt: "Experiência cinematográfica · carro 3D em tempo real", en: "Cinematic experience · real-time 3D car", es: "Experiencia cinematográfica · auto 3D en tiempo real" },
    problem: { pt: "Site de produto premium quase sempre vira catálogo estático: não transmite a sensação da marca nem dá vontade de explorar.", en: "Premium product sites almost always end up as static catalogs: they carry none of the brand's feeling and give no reason to explore.", es: "El sitio de un producto premium casi siempre termina en catálogo estático: no transmite la sensación de la marca ni dan ganas de explorar." },
    result: { pt: "Um comercial de carro de luxo navegável: filme em 14 cenas dirigido pelo scroll (a câmera muda, o carro gira, as luzes acendem), closeups de design, números contando, galeria-showroom horizontal e configurador 3D. Pintura, rodas, luz de cabine e underglow mudam o carro em tempo real, com preço reativo.", en: "A navigable luxury-car commercial: a 14-scene film directed by scroll (the camera moves, the car turns, lights ignite), design close-ups, counting numbers, a horizontal showroom gallery and a 3D configurator. Paint, wheels, cabin light and underglow change the car in real time, with a reactive price.", es: "Un comercial de auto de lujo navegable: película en 14 escenas dirigida por el scroll (la cámara cambia, el auto gira, las luces se encienden), closeups de diseño, números que cuentan, galería-showroom horizontal y configurador 3D. Pintura, ruedas, luz de cabina y underglow cambian el auto en tiempo real, con precio reactivo." },
    stack: ["Next.js", "TypeScript", "React Three Fiber", "Three.js", "GSAP", "Lenis", "Tailwind"],
    metric: { pt: "Filme em 14 cenas · configurador 3D", en: "14-scene film · 3D configurator", es: "Película en 14 escenas · configurador 3D" },
    status: { pt: "Projeto autoral · no ar", en: "Personal project · live", es: "Proyecto propio · en línea" },
    live: "https://aurex-motors-ecru.vercel.app",
    repos: [{ label: "Código", url: `${GH}/aurex-motors` }],
    featured: true,
    image: "/shots/aurex-motors.webp",
    imageStatic: true,
    caseStudy: {
      narrative: [
        {
          pt: "A arquitetura separa o mundo DOM do mundo 3D por um estado mutável compartilhado (world.ts). Um ScrollTrigger por seção escreve (cena, progresso) e o rig de câmera lê isso a cada frame dentro do canvas, então o scroll nunca re-renderiza React. O roteiro do filme vive num arquivo só (scenes.ts), com keyframes de posição, alvo e fov da câmera, rotação do carro e intensidade de cada luz por cena, interpolados com damping exponencial. É o damping que transforma cortes secos em movimentos de dolly. Por cima, parallax de mouse desloca câmera e key light, então os reflexos na lataria seguem o cursor.",
          en: "The architecture splits the DOM world from the 3D world with a shared mutable state (world.ts). One ScrollTrigger per section writes (scene, progress) and the camera rig reads it every frame inside the canvas, so scroll never re-renders React. The film script lives in a single file (scenes.ts), with per-scene keyframes for camera position, target and fov, car rotation and every light's intensity, interpolated with exponential damping. The damping is what turns hard cuts into dolly moves. On top, mouse parallax offsets the camera and key light, so the paint reflections follow the cursor.",
          es: "La arquitectura separa el mundo DOM del mundo 3D por un estado mutable compartido (world.ts). Un ScrollTrigger por sección escribe (escena, progreso) y el rig de cámara lo lee en cada frame dentro del canvas, así que el scroll nunca re-renderiza React. El guion de la película vive en un solo archivo (scenes.ts), con keyframes de posición, objetivo y fov de la cámara, rotación del auto e intensidad de cada luz por escena, interpolados con damping exponencial. Es el damping lo que transforma cortes secos en movimientos de dolly. Encima, el paralaje de mouse desplaza cámara y key light, así que los reflejos en la carrocería siguen al cursor.",
        },
        {
          pt: "O carro é o Ferrari 458 dos exemplos oficiais do three.js (GLB com Draco, decoder servido localmente, zero CDN), rebrandizado por nome de material em runtime: pintura vira MeshPhysicalMaterial configurável com clearcoat, acentos amarelos viram vermelho AUREX, faróis e lanternas viram emissivos ligados ao roteiro (acendem na cena certa), cromados viram satin escuro e o interior vira couro preto com friso vermelho. O configurador escreve direto no estado compartilhado e o carro faz lerp dos materiais por frame, então a troca de cor é líquida, sem nenhum re-render da árvore 3D. O estúdio é 100% procedural: Lightformers no lugar de HDRI, piso MeshReflectorMaterial e cones aditivos como luz volumétrica.",
          en: "The car is the Ferrari 458 from the official three.js examples (Draco-compressed GLB, decoder served locally, zero CDN), rebranded by material name at runtime: paint becomes a configurable clearcoat MeshPhysicalMaterial, yellow accents become AUREX red, head and taillights become script-driven emissives (they ignite on cue), chrome goes satin dark and the interior becomes black leather with red piping. The configurator writes straight into the shared state and the car lerps its materials per frame, so color changes feel liquid, with zero 3D-tree re-renders. The studio is fully procedural: Lightformers instead of HDRIs, a MeshReflectorMaterial floor and additive cones as volumetric shafts.",
          es: "El auto es el Ferrari 458 de los ejemplos oficiales de three.js (GLB con Draco, decoder servido localmente, cero CDN), rebrandeado por nombre de material en runtime: la pintura pasa a ser un MeshPhysicalMaterial configurable con clearcoat, los acentos amarillos pasan a rojo AUREX, faros y luces traseras se vuelven emisivos ligados al guion (se encienden en la escena correcta), los cromados pasan a satín oscuro y el interior se vuelve cuero negro con ribete rojo. El configurador escribe directo en el estado compartido y el auto hace lerp de los materiales por frame, así que el cambio de color es líquido, sin ningún re-render del árbol 3D. El estudio es 100% procedural: Lightformers en lugar de HDRI, piso MeshReflectorMaterial y conos aditivos como luz volumétrica.",
        },
        {
          pt: "Performance e robustez: o PerformanceMonitor degrada o DPR automaticamente em GPU fraca, o canvas principal pausa (frameloop never) quando a galeria, que tem canvas próprio, cobre a tela, o Lenis desliga em touch e o prefers-reduced-motion troca todo damping por poses instantâneas. O debug rendeu gotchas documentados: o GSAP interpreta translateY(115%) inline como pixels (o certo é animar y, não yPercent), CSS fora de @layer vence qualquer utility no Tailwind v4, e o Chromium headless renderiza a ~1fps. Câmera com damping nunca converge em screenshot, e isso virou um modo ?snap de validação visual.",
          en: "Performance and robustness: PerformanceMonitor steps the DPR down on weak GPUs, the main canvas pauses (frameloop never) while the gallery, which owns its own canvas, covers the screen, Lenis is disabled on touch and prefers-reduced-motion swaps all damping for instant poses. Debugging produced documented gotchas: GSAP parses inline translateY(115%) as pixels (animate y, not yPercent), un-layered CSS beats any utility in Tailwind v4, and headless Chromium renders at ~1fps. A damped camera never converges in screenshots, which became a ?snap visual-testing mode.",
          es: "Performance y robustez: el PerformanceMonitor degrada el DPR automáticamente en GPU débil, el canvas principal se pausa (frameloop never) cuando la galería, que tiene canvas propio, cubre la pantalla, Lenis se apaga en touch y prefers-reduced-motion cambia todo damping por poses instantáneas. El debug dejó gotchas documentados: GSAP interpreta translateY(115%) inline como píxeles (lo correcto es animar y, no yPercent), el CSS fuera de @layer le gana a cualquier utility en Tailwind v4, y Chromium headless renderiza a ~1fps. Una cámara con damping nunca converge en screenshot, y eso se convirtió en un modo ?snap de validación visual.",
        },
      ],
      highlights: [
        { label: { pt: "Roteiro de câmera em arquivo único", en: "Single-file camera script", es: "Guion de cámara en archivo único" }, detail: { pt: "14 cenas com keyframes de câmera, rotação e luzes, dirigidas pelo scroll com damping exponencial.", en: "14 scenes of camera, rotation and light keyframes, scroll-directed with exponential damping.", es: "14 escenas con keyframes de cámara, rotación y luces, dirigidas por el scroll con damping exponencial." } },
        { label: { pt: "Configurador sem re-render", en: "Re-render-free configurator", es: "Configurador sin re-render" }, detail: { pt: "Painel escreve num estado compartilhado; o carro faz lerp de materiais por frame.", en: "The panel writes to shared state; the car lerps materials per frame.", es: "El panel escribe en un estado compartido; el auto hace lerp de materiales por frame." } },
        { label: { pt: "Zero downloads externos", en: "Zero external downloads", es: "Cero descargas externas" }, detail: { pt: "Modelo local, decoder Draco local e ambiente por Lightformers, sem HDRI nem CDN.", en: "Local model, local Draco decoder and Lightformer environment, with no HDRIs and no CDNs.", es: "Modelo local, decoder Draco local y ambiente por Lightformers, sin HDRI ni CDN." } },
      ],
      gallery: [
        { src: "/shots/aurex-motors/config.webp", alt: { pt: "Configurador 3D com pintura, rodas e cabine em tempo real", en: "3D configurator with real-time paint, wheels and cabin", es: "Configurador 3D con pintura, ruedas y cabina en tiempo real" } },
        { src: "/shots/aurex-motors/tail.webp", alt: { pt: "Cena traseira do filme com a lanterna acesa", en: "Rear film scene with the taillight lit", es: "Escena trasera de la película con la luz trasera encendida" } },
      ],
    },
  },
  {
    slug: "atelier-vertex",
    homeFeatured: true,
    category: "landing-premium",
    title: "ATELIER VERTEX",
    tagline: { pt: "Scrollytelling arquitetônico · vídeo real controlado pelo scroll", en: "Architectural scrollytelling · real footage driven by scroll", es: "Scrollytelling arquitectónico · video real controlado por el scroll" },
    problem: { pt: "Site de escritório de arquitetura quase sempre é catálogo de fotos estáticas. Mostra só o resultado, nunca o processo, e não convence quem valoriza execução.", en: "Architecture firm sites are almost always static photo catalogs. They show the result, never the process, and don't convince clients who value execution.", es: "El sitio de un estudio de arquitectura casi siempre es un catálogo de fotos estáticas. Muestra solo el resultado, nunca el proceso, y no convence a quien valora la ejecución." },
    result: { pt: "Um filme real de obra (do andaime à fachada pronta) cujo tempo de vídeo é 100% amarrado ao scroll, sem autoplay: rolar constrói o prédio, voltar desconstrói. A planta baixa se desenha sobre o vídeo como numa mesa de luz, uma linha de cota mede a obra em dias, e depois do filme o site vira o arquivo completo do estúdio, com obras entregues, processo e contato.", en: "A real construction film (from scaffolding to finished façade) whose video time is 100% tied to scroll, with no autoplay: scrolling down builds the building, scrolling up tears it down. The floor plan draws itself over the video like on a light table, a dimension line measures the build in days, and after the film the site becomes the studio's full archive, with delivered work, process and contact.", es: "Una película real de obra (del andamio a la fachada terminada) cuyo tiempo de video está 100% amarrado al scroll, sin autoplay: bajar construye el edificio, subir lo deconstruye. La planta se dibuja sobre el video como en una mesa de luz, una línea de cota mide la obra en días, y después de la película el sitio se convierte en el archivo completo del estudio, con obras entregadas, proceso y contacto." },
    stack: ["Next.js", "TypeScript", "GSAP", "ScrollTrigger", "Lenis", "Tailwind", "FFmpeg"],
    metric: { pt: "Vídeo real · 100% controlado pelo scroll", en: "Real footage · 100% scroll-controlled", es: "Video real · 100% controlado por el scroll" },
    status: { pt: "Projeto autoral · no ar", en: "Personal project · live", es: "Proyecto propio · en línea" },
    live: "https://atelier-vertex-v2.vercel.app",
    repos: [{ label: "Código", url: `${GH}/atelier-vertex-v2` }],
    featured: true,
    image: "/shots/atelier-vertex.webp",
    imageStatic: true,
    caseStudy: {
      narrative: [
        {
          pt: "A arquitetura separa o vídeo do scroll do DOM por um estado mutável compartilhado (world.ts), a mesma base do AUREX MOTORS. Um ScrollTrigger por seção escreve (cena, progresso) e um rAF lê isso a cada frame pra perseguir o currentTime do vídeo com damping, então pular de cena vira um dolly de tempo, nunca um corte seco. O roteiro do filme vive num arquivo único (scenes.ts) mapeando cada cena a uma fração da duração do vídeo. O vídeo em si é codificado com GOP 1, ou seja, todo frame é keyframe, porque sem isso o seek durante o scrub engasga. O preço é um arquivo maior, pago conscientemente.",
          en: "The architecture splits video from scroll via a shared mutable state (world.ts), the same base as AUREX MOTORS. One ScrollTrigger per section writes (scene, progress), and a rAF loop reads it every frame to chase the video's currentTime with damping, so jumping scenes becomes a time dolly, never a hard cut. The film's script lives in one file (scenes.ts) mapping each scene to a fraction of the video's duration. The video itself is encoded with GOP 1, meaning every frame is a keyframe, because without it seeking during scrub stutters. The tradeoff is a larger file, paid knowingly.",
          es: "La arquitectura separa el video del scroll del DOM por un estado mutable compartido (world.ts), la misma base de AUREX MOTORS. Un ScrollTrigger por sección escribe (escena, progreso) y un rAF lo lee en cada frame para perseguir el currentTime del video con damping, así que saltar de escena se vuelve un dolly de tiempo, nunca un corte seco. El guion de la película vive en un archivo único (scenes.ts) que mapea cada escena a una fracción de la duración del video. El video en sí está codificado con GOP 1, es decir, todo frame es keyframe, porque sin eso el seek durante el scrub se traba. El precio es un archivo más grande, pagado a conciencia.",
        },
        {
          pt: "A cena mais autoral é a 'Prancha': o vídeo escurece até virar uma mesa de luz e a planta do pavimento tipo se desenha amarrada ao scroll, com paredes, mobiliário, linhas de cota com medidas reais e um carimbo de prancha, usando a mesma técnica de pathLength=1 de um projeto anterior da família. As fronteiras do roteiro não foram chute. Extraí frames do vídeo-fonte a cada 0,5s pra achar onde a transformação visual acontece de verdade, que ficou concentrada entre 40% e 70% da duração, e recalibrei as cenas pra que 'Vedação' e 'Fachada' realmente parecessem etapas diferentes. Antes disso, duas das três cenas mostravam praticamente o mesmo andaime parado.",
          en: "The most distinctive scene is 'Prancha' (Blueprint): the video darkens into a light table and the floor plan draws itself in sync with scroll, with walls, furniture, dimension lines carrying real measurements and a drafting stamp, using the same pathLength=1 technique from an earlier project in the same family. The script's boundaries weren't guessed. I extracted frames from the source video every 0.5s to find where the real visual transformation happens, which turned out to be concentrated between 40% and 70% of the duration, then recalibrated the scenes so 'Vedação' and 'Fachada' actually read as different stages. Before that fix, two of the three scenes showed nearly the same static scaffolding.",
          es: "La escena más personal es la \'Prancha\' (Lámina): el video se oscurece hasta volverse una mesa de luz y la planta del piso tipo se dibuja amarrada al scroll, con paredes, mobiliario, líneas de cota con medidas reales y un sello de lámina, usando la misma técnica de pathLength=1 de un proyecto anterior de la familia. Las fronteras del guion no fueron un tanteo. Extraje frames del video fuente cada 0,5s para encontrar dónde ocurre de verdad la transformación visual, que quedó concentrada entre el 40% y el 70% de la duración, y recalibré las escenas para que \'Vedação\' y \'Fachada\' realmente parecieran etapas distintas. Antes de eso, dos de las tres escenas mostraban prácticamente el mismo andamio quieto.",
        },
        {
          pt: "Como no projeto anterior de estádios, o site passou por uma auto-auditoria crítica de design (hero, storytelling, UX, UI, responsividade, nota 0-10 por eixo), rodada contra o próprio build de produção e não contra a intenção. O achado mais grave foi o header fixo, que não tinha fundo opaco de verdade: qualquer título claro passando por baixo dele durante o scroll virava texto sobre texto ilegível. A correção revelou um gotcha sutil de CSS. Um 'backdrop-filter' no header vira containing block pra 'position: fixed', então o menu mobile em tela cheia estava sendo calculado relativo à altura do próprio header, não do viewport, até o painel ser movido pra fora do elemento. Depois da auditoria entraram navegação mobile com hambúrguer de verdade, CTAs diferenciados (um fecha o filme, só o outro converte), trilho de progresso do filme e um cursor customizado.",
          en: "Like the earlier stadiums project, the site went through a critical self-audit of its design (hero, storytelling, UX, UI, responsiveness, scored 0-10 per axis), run against the actual production build rather than against intent. The most serious finding was the fixed header, which had no real opaque background: any light-colored heading scrolling underneath it turned into illegible text-on-text. The fix surfaced a subtle CSS gotcha. A 'backdrop-filter' on the header becomes a containing block for 'position: fixed', so the fullscreen mobile menu was being sized relative to the header's own height instead of the viewport, until the panel was moved outside that element. After the audit came a real hamburger mobile nav, differentiated CTAs (one closes the film, only the other converts), a film progress rail and a custom cursor.",
          es: "Como en el proyecto anterior de estadios, el sitio pasó por una autoauditoría crítica de diseño (hero, storytelling, UX, UI, responsividad, nota 0-10 por eje), corrida contra el propio build de producción y no contra la intención. El hallazgo más grave fue el header fijo, que no tenía fondo opaco de verdad: cualquier título claro que pasara por debajo durante el scroll se convertía en texto sobre texto ilegible. La corrección reveló un gotcha sutil de CSS. Un \'backdrop-filter\' en el header se vuelve containing block para \'position: fixed\', así que el menú mobile a pantalla completa se estaba calculando relativo a la altura del propio header, no del viewport, hasta que el panel se movió fuera del elemento. Después de la auditoría entraron navegación mobile con hamburguesa de verdad, CTAs diferenciados (uno cierra la película, solo el otro convierte), riel de progreso de la película y un cursor personalizado.",
        },
      ],
      highlights: [
        { label: { pt: "Vídeo 100% scroll-driven", en: "100% scroll-driven video", es: "Video 100% scroll-driven" }, detail: { pt: "Sem autoplay: currentTime do vídeo perseguido por rAF com damping, GOP 1 pra seek instantâneo.", en: "No autoplay: video currentTime chased by a damped rAF loop, GOP 1 for instant seek.", es: "Sin autoplay: currentTime del video perseguido por rAF con damping, GOP 1 para seek instantáneo." } },
        { label: { pt: "Planta que se desenha", en: "Self-drawing floor plan", es: "Planta que se dibuja sola" }, detail: { pt: "Cena 'Prancha' com paredes, cotas e carimbo desenhados ao vivo sobre o vídeo escurecido.", en: "'Blueprint' scene with walls, dimensions and stamp drawn live over the dimmed video.", es: "Escena \'Prancha\' con paredes, cotas y sello dibujados en vivo sobre el video oscurecido." } },
        { label: { pt: "Auto-auditoria de design", en: "Design self-audit", es: "Autoauditoría de diseño" }, detail: { pt: "Parecer crítico 0-10 rodado contra o build real; achou e corrigiu um bug de nav ilegível e outro de menu mobile quebrado.", en: "Critical 0-10 review run against the real build; found and fixed an illegible nav bug and a broken mobile menu.", es: "Dictamen crítico 0-10 corrido contra el build real; encontró y corrigió un bug de nav ilegible y otro de menú mobile roto." } },
      ],
      gallery: [
        { src: "/shots/atelier-vertex/prancha.webp", alt: { pt: "Planta do pavimento tipo se desenhando sobre o vídeo escurecido", en: "Floor plan drawing itself over the dimmed video", es: "Planta del piso tipo dibujándose sobre el video oscurecido" } },
        { src: "/shots/atelier-vertex/entregue.webp", alt: { pt: "Cena final do filme com o prédio pronto e CTA", en: "Final film scene with the finished building and CTA", es: "Escena final de la película con el edificio terminado y CTA" } },
      ],
    },
  },
  {
    slug: "aurex-timepieces",
    category: "landing-premium",
    title: "AUREX TIMEPIECES",
    tagline: { pt: "Experiência cinematográfica · relógio 3D que desmonta no scroll", en: "Cinematic experience · a 3D watch that disassembles on scroll", es: "Experiencia cinematográfica · reloj 3D que se desarma con el scroll" },
    problem: { pt: "Relojoaria de luxo na web quase sempre é foto de produto parada, que não transmite a complexidade mecânica capaz de justificar o preço.", en: "Luxury watches on the web are almost always static product photos, which never convey the mechanical complexity that justifies the price.", es: "La relojería de lujo en la web casi siempre es foto de producto quieta, que no transmite la complejidad mecánica capaz de justificar el precio." },
    result: { pt: "Um relógio 100% procedural (Calibre AX-01 Tourbillon) que desmonta peça por peça conforme o scroll (caixa, bezel, coroa, mostrador, ponteiros, trem de engrenagens, mola espiral, escape, rotor e a gaiola giratória do tourbillon) e remonta no caminho inverso exato. Filme em 15 cenas, configurador com troca de material em tempo real e galeria 360° por arrasto.", en: "A 100% procedural watch (Calibre AX-01 Tourbillon) that disassembles piece by piece as you scroll (case, bezel, crown, dial, hands, gear train, mainspring, escapement, rotor and the tourbillon's spinning cage), then reassembles along the exact reverse path. A 15-scene film, a real-time material configurator and a drag-to-rotate 360° gallery.", es: "Un reloj 100% procedural (Calibre AX-01 Tourbillon) que se desarma pieza por pieza según el scroll (caja, bisel, corona, esfera, manecillas, tren de engranajes, muelle real, escape, rotor y la jaula giratoria del tourbillon) y se rearma por el camino inverso exacto. Película en 15 escenas, configurador con cambio de material en tiempo real y galería 360° por arrastre." },
    stack: ["Next.js", "TypeScript", "React Three Fiber", "Three.js", "GSAP", "Lenis", "Tailwind"],
    metric: { pt: "15 cenas · relógio 100% procedural", en: "15 scenes · 100% procedural watch", es: "15 escenas · reloj 100% procedural" },
    status: { pt: "Projeto autoral · no ar", en: "Personal project · live", es: "Proyecto propio · en línea" },
    live: "https://aurex-timepieces.vercel.app",
    repos: [{ label: "Código", url: `${GH}/aurex-timepieces` }],
    featured: true,
    image: "/shots/aurex-timepieces.webp",
    imageStatic: true,
    caseStudy: {
      narrative: [
        {
          pt: "Herda a arquitetura de estado compartilhado do AUREX MOTORS (canvas fixo, roteiro de cenas em arquivo único, câmera com damping), mas o diferencial é o sistema de desmontagem. Cada componente do relógio é um <Part> com posição de origem, deslocamento, rotação e uma janela de progresso (delay/span) própria. Uma função de smoothstep lê um valor global de 'explosão' e cada peça sai e volta em cascata dentro da sua janela. A remontagem não é uma animação separada: é o caminho de saída percorrido ao contrário.",
          en: "It inherits the shared-state architecture from AUREX MOTORS (fixed canvas, single-file scene script, damped camera), but the differentiator is the disassembly system. Every watch component is a <Part> with a home position, offset, rotation and its own progress window (delay/span). A smoothstep function reads a global 'explode' value and each piece slides out and back in cascade within its window. Reassembly isn't a separate animation: it's the exact same exit path walked backwards.",
          es: "Hereda la arquitectura de estado compartido de AUREX MOTORS (canvas fijo, guion de escenas en archivo único, cámara con damping), pero el diferencial es el sistema de desarme. Cada componente del reloj es un <Part> con posición de origen, desplazamiento, rotación y una ventana de progreso (delay/span) propia. Una función de smoothstep lee un valor global de \'explosión\' y cada pieza sale y vuelve en cascada dentro de su ventana. El rearmado no es una animación separada: es el camino de salida recorrido al revés.",
        },
        {
          pt: "O relógio é 100% procedural: caixa em anel (ExtrudeGeometry com furo, não um cilindro sólido), bezel, coroa serrilhada, mostrador com índices instanciados, cinco engrenagens paramétricas com dentes instanciados, mola espiral como tubo em espiral de Arquimedes, escape oscilante e a gaiola giratória do tourbillon com seu próprio balanço. Um bug real ilustra o valor de instrumentar em vez de adivinhar. A caixa começou como cilindro sólido, e a tampa frontal, invisível pra intuição, tapou o mostrador durante toda uma sessão de trabalho. O diagnóstico só veio de um raycast do centro da tela listando os hits em ordem, que expôs o cilindro a 6cm na frente do dial.",
          en: "The watch is 100% procedural: a ring-shaped case (a hollowed ExtrudeGeometry, not a solid cylinder), a bezel, a knurled crown, a dial with instanced hour markers, five parametric gears with instanced teeth, a mainspring built as an Archimedean-spiral tube, an oscillating escapement and the tourbillon's own spinning cage with its balance wheel. One real bug shows the value of instrumenting instead of guessing. The case started as a solid cylinder, and its front cap, invisible to intuition, hid the dial for an entire work session. The diagnosis only came from a raycast fired from screen center listing hits in order, which exposed the cylinder sitting 6cm in front of the dial.",
          es: "El reloj es 100% procedural: caja en anillo (ExtrudeGeometry con agujero, no un cilindro sólido), bisel, corona estriada, esfera con índices instanciados, cinco engranajes paramétricos con dientes instanciados, muelle real como tubo en espiral de Arquímedes, escape oscilante y la jaula giratoria del tourbillon con su propio volante. Un bug real ilustra el valor de instrumentar en vez de adivinar. La caja empezó como cilindro sólido, y la tapa frontal, invisible para la intuición, tapó la esfera durante toda una sesión de trabajo. El diagnóstico solo vino de un raycast desde el centro de la pantalla listando los hits en orden, que expuso el cilindro a 6cm delante del dial.",
        },
        {
          pt: "O maior salto de realismo custou zero geometria extra: uma CanvasTexture impressa sobre o mostrador (trilha dos minutos, nome da marca, numerais) resolveu o que nenhuma troca de material resolvia sozinha. O vidro também exigiu um ajuste contraintuitivo. MeshPhysicalMaterial transparente em ângulo raso reflete quase 100% da luz direta por Fresnel, criando um véu leitoso sobre o mostrador independente da opacidade. A solução foi um MeshBasicMaterial com tinta constante, deixando os reflexos por conta só dos metais.",
          en: "The biggest realism jump cost zero extra geometry: a CanvasTexture printed onto the dial (minute track, brand name, numerals) solved what no material swap could fix alone. Glass also demanded a counter-intuitive call. A transparent MeshPhysicalMaterial at a grazing angle reflects almost 100% of direct light through Fresnel, creating a milky veil over the dial regardless of opacity. The fix was a MeshBasicMaterial with a constant tint, leaving reflections entirely to the metal parts.",
          es: "El mayor salto de realismo costó cero geometría extra: una CanvasTexture impresa sobre la esfera (minutería, nombre de la marca, numerales) resolvió lo que ningún cambio de material resolvía por sí solo. El vidrio también exigió un ajuste contraintuitivo. Un MeshPhysicalMaterial transparente en ángulo rasante refleja casi el 100% de la luz directa por Fresnel, creando un velo lechoso sobre la esfera independiente de la opacidad. La solución fue un MeshBasicMaterial con tinte constante, dejando los reflejos solo a cargo de los metales.",
        },
      ],
      highlights: [
        { label: { pt: "Sistema de explosão modular", en: "Modular explosion system", es: "Sistema de explosión modular" }, detail: { pt: "Cada peça com janela própria de saída/retorno; remontagem é o caminho inverso exato, não uma animação separada.", en: "Each part has its own exit/return window; reassembly is the exact reverse path, not a separate animation.", es: "Cada pieza con ventana propia de salida/retorno; el rearmado es el camino inverso exacto, no una animación separada." } },
        { label: { pt: "Debug por raycast", en: "Raycast-driven debugging", es: "Debug por raycast" }, detail: { pt: "Bug de geometria sólida tapando o mostrador só foi achado listando hits de um raycast, não por tentativa e erro visual.", en: "A solid-geometry bug hiding the dial was only found by listing raycast hits, not by visual trial and error.", es: "El bug de geometría sólida tapando la esfera solo se encontró listando hits de un raycast, no por prueba y error visual." } },
        { label: { pt: "Realismo via CanvasTexture", en: "Realism via CanvasTexture", es: "Realismo vía CanvasTexture" }, detail: { pt: "Impressão do mostrador (trilha de minutos, marca) foi o maior ganho visual do projeto, sem custo de geometria.", en: "The printed dial (minute track, brand) was the project's single biggest visual win, at zero geometry cost.", es: "La impresión de la esfera (minutería, marca) fue la mayor ganancia visual del proyecto, sin costo de geometría." } },
      ],
      gallery: [
        { src: "/shots/aurex-timepieces/config.webp", alt: { pt: "Configurador com troca de caixa, mostrador, ponteiros e pulseira em tempo real", en: "Configurator with real-time case, dial, hands and strap swaps", es: "Configurador con cambio de caja, esfera, manecillas y correa en tiempo real" } },
        { src: "/shots/aurex-timepieces/colecao.webp", alt: { pt: "Vitrine da coleção com as quatro expressões do calibre", en: "Collection showcase with the calibre's four expressions", es: "Vitrina de la colección con las cuatro expresiones del calibre" } },
      ],
    },
  },
  {
    slug: "age-of-dragons",
    category: "landing-premium",
    title: "THE AGE OF DRAGONS",
    tagline: { pt: "Biblioteca proibida dos dragões · documentário interativo em 8 capítulos", en: "The dragons' forbidden library · an 8-chapter interactive documentary", es: "Biblioteca prohibida de los dragones · documental interactivo en 8 capítulos" },
    problem: { pt: "Sites sobre mitologia e cultura pop viram enciclopédia: texto corrido, imagem estática, zero imersão. Nada do peso cinematográfico que o tema pede.", en: "Mythology and pop-culture sites default to encyclopedia mode: running text, static images, zero immersion. None of the cinematic weight the subject deserves.", es: "Los sitios sobre mitología y cultura pop se vuelven enciclopedia: texto corrido, imagen estática, cero inmersión. Nada del peso cinematográfico que el tema pide." },
    result: { pt: "Uma experiência-conceito que entra numa biblioteca ancestral proibida: hero em vídeo fullscreen com o dragão surgindo do relâmpago, cursor de brasa, cinzas subindo e trovão ocasional, mais 8 capítulos que cruzam mito e ficção. Tem o nascimento do dragão em 6 mitologias (China, Japão, Europa medieval, Nórdica, Maia, Celta), os 10 dragões mais icônicos da ficção em cards 3D com glifo autoral próprio (sem usar still oficial de nenhuma obra), mapa mundial clicável, linha do tempo horizontal pinada no scroll, galeria de gravuras em domínio público, tabela comparativa de poder e uma silhueta final batendo asas devagar.", en: "A concept experience that opens into a forbidden ancient library: fullscreen video hero with the dragon emerging from lightning, an ember cursor, rising ash and occasional thunder, plus 8 chapters bridging myth and fiction. It covers the dragon's birth across 6 mythologies (China, Japan, medieval Europe, Norse, Maya, Celtic), fiction's 10 most iconic dragons in 3D cards with an original glyph mark each (no official stills used), a clickable world map, a horizontal timeline pinned on scroll, a gallery of public-domain engravings, a power comparison table and a final silhouette slowly beating its wings.", es: "Una experiencia-concepto que entra en una biblioteca ancestral prohibida: hero en video fullscreen con el dragón surgiendo del relámpago, cursor de brasa, cenizas subiendo y truenos ocasionales, más 8 capítulos que cruzan mito y ficción. Tiene el nacimiento del dragón en 6 mitologías (China, Japón, Europa medieval, Nórdica, Maya, Celta), los 10 dragones más icónicos de la ficción en cards 3D con glifo propio original (sin usar ningún still oficial de ninguna obra), mapa mundial clicable, línea de tiempo horizontal fijada al scroll, galería de grabados de dominio público, tabla comparativa de poder y una silueta final batiendo las alas despacio." },
    stack: ["Next.js", "TypeScript", "GSAP", "ScrollTrigger", "Lenis", "Framer Motion", "Tailwind"],
    metric: { pt: "8 capítulos · 10 dragões · 6 mitologias", en: "8 chapters · 10 dragons · 6 mythologies", es: "8 capítulos · 10 dragones · 6 mitologías" },
    status: { pt: "Projeto autoral · no ar", en: "Personal project · live", es: "Proyecto propio · en línea" },
    live: "https://age-of-dragons.vercel.app",
    featured: false,
    image: "/shots/age-of-dragons.webp",
    imageStatic: true,
    caseStudy: {
      narrative: [
        {
          pt: "A restrição legal virou a decisão de design mais forte do projeto. Os 10 dragões de ficção (Smaug, Drogon, Balerion, Alduin...) são propriedade intelectual protegida, então cada card recebeu um glifo próprio no lugar de qualquer still oficial: traço minimalista em SVG, com cor exclusiva por universo. As seções históricas, por sua vez, usam só arte de domínio público (Hokusai, Dürer, Doré, Chen Rong), curada e verificada uma a uma na API do Wikimedia Commons antes de entrar no site.",
          en: "The legal constraint became the project's strongest design decision. The 10 fictional dragons (Smaug, Drogon, Balerion, Alduin...) are protected IP, so each card got its own mark instead of any official still: a minimalist SVG line drawing in a color unique to its universe. The historical sections, in turn, use only public-domain art (Hokusai, Dürer, Doré, Chen Rong), curated and individually verified via the Wikimedia Commons API before going live.",
          es: "La restricción legal se convirtió en la decisión de diseño más fuerte del proyecto. Los 10 dragones de ficción (Smaug, Drogon, Balerion, Alduin...) son propiedad intelectual protegida, así que cada card recibió un glifo propio en lugar de cualquier still oficial: trazo minimalista en SVG, con color exclusivo por universo. Las secciones históricas, a su vez, usan solo arte de dominio público (Hokusai, Dürer, Doré, Chen Rong), curado y verificado uno por uno en la API de Wikimedia Commons antes de entrar al sitio.",
        },
        {
          pt: "O motor cinematográfico é uma única ilha client-side: Lenis cuida do scroll fluido, ScrollTrigger dispara as revelações letra por letra (SplitText) e o pin horizontal da linha do tempo, e cada card 3D segue o mouse com uma luz vermelha radial ancorada em variáveis CSS (--mx/--my) atualizadas a cada frame. É o mesmo padrão de cursor amortecido (quickTo) usado nos projetos-irmãos, aqui com direção de arte gótica: preto profundo, vermelho fogo, dourado antigo.",
          en: "The cinematic engine is a single client-side island: Lenis handles smooth scroll, ScrollTrigger fires the letter-by-letter reveals (SplitText) and the timeline's horizontal pin, and each 3D card follows the cursor with a radial red light anchored to CSS variables (--mx/--my) updated every frame. It's the same damped-cursor pattern (quickTo) used in sibling projects, here art-directed toward deep black, fire red and old gold.",
          es: "El motor cinematográfico es una única isla client-side: Lenis se encarga del scroll fluido, ScrollTrigger dispara las revelaciones letra por letra (SplitText) y el pin horizontal de la línea de tiempo, y cada card 3D sigue al mouse con una luz roja radial anclada en variables CSS (--mx/--my) actualizadas en cada frame. Es el mismo patrón de cursor amortiguado (quickTo) usado en los proyectos hermanos, aquí con dirección de arte gótica: negro profundo, rojo fuego, dorado antiguo.",
        },
      ],
      highlights: [
        { label: { pt: "IP-safe por design", en: "IP-safe by design", es: "IP-safe por diseño" }, detail: { pt: "Glifos SVG autorais por dragão de ficção, zero still oficial. A restrição legal virou identidade visual.", en: "Original SVG glyphs per fictional dragon, zero official stills. The legal constraint became the visual identity.", es: "Glifos SVG originales por dragón de ficción, cero stills oficiales. La restricción legal se convirtió en identidad visual." } },
        { label: { pt: "Arte 100% domínio público", en: "100% public-domain art", es: "Arte 100% dominio público" }, detail: { pt: "Toda peça histórica veio do Wikimedia Commons, verificada individualmente antes do upload.", en: "Every historical artwork came from Wikimedia Commons, individually verified before upload.", es: "Toda pieza histórica vino de Wikimedia Commons, verificada individualmente antes del upload." } },
        { label: { pt: "Cards com luz seguindo o mouse", en: "Cards with mouse-tracked light", es: "Cards con luz que sigue al mouse" }, detail: { pt: "Tilt 3D + glow vermelho radial em variáveis CSS, atualizado a cada frame via GSAP quickTo.", en: "3D tilt + radial red glow driven by CSS variables, updated every frame via GSAP quickTo.", es: "Tilt 3D + glow rojo radial en variables CSS, actualizado en cada frame vía GSAP quickTo." } },
      ],
      gallery: [
        { src: "/shots/age-of-dragons/lendarios.webp", alt: { pt: "Cards dos 10 dragões mais icônicos da ficção com glifo autoral e luz vermelha ao mouse", en: "Cards for fiction's 10 most iconic dragons with original glyphs and mouse-tracked red light", es: "Cards de los 10 dragones más icónicos de la ficción con glifo original y luz roja al mouse" } },
        { src: "/shots/age-of-dragons/mapa.webp", alt: { pt: "Mapa mundial clicável com as 6 mitologias do dragão", en: "Clickable world map with the dragon's 6 mythologies", es: "Mapa mundial clicable con las 6 mitologías del dragón" } },
        { src: "/shots/age-of-dragons/timeline.webp", alt: { pt: "Linha do tempo horizontal pinada no scroll, de 1750 a.C. à era do streaming", en: "Horizontal timeline pinned on scroll, from 1750 BCE to the streaming era", es: "Línea de tiempo horizontal fijada al scroll, del 1750 a. C. a la era del streaming" } },
        { src: "/shots/age-of-dragons/final.webp", alt: { pt: "Silhueta final do dragão batendo asas devagar sobre o encerramento", en: "Final dragon silhouette slowly beating its wings over the closing section", es: "Silueta final del dragón batiendo las alas despacio sobre el cierre" } },
      ],
    },
  },
];
